### ISSUE TITLE
Publish a new version to npm

### ISSUE THREAD

**Issue by nik-kor** [betaagency-os/declint-ru#2]
We need a new one)

**Comment by Bubujka** [comment]
Так сразу же и обновил в npm, не?
http://ss.bubujka.org/2016/11/02/11-29-24_cea0da2b12.png

**Comment by nik-kor** [comment]
все так)

Смутила старая версия в`package.json`

**Comment by Bubujka** [comment]
Прости пожалуйста. А вот запушить - забыл =_=
